// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gotest.proto

package goserbench

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	BirthDay             int64    `protobuf:"varint,5,opt,name=birthDay,proto3" json:"birthDay,omitempty"`
	Spouse               bool     `protobuf:"varint,6,opt,name=spouse,proto3" json:"spouse,omitempty"`
	Money                float64  `protobuf:"fixed64,7,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoUser) Reset()         { *m = GoUser{} }
func (m *GoUser) String() string { return proto.CompactTextString(m) }
func (*GoUser) ProtoMessage()    {}
func (*GoUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3906679705eecf0, []int{0}
}

func (m *GoUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoUser.Unmarshal(m, b)
}
func (m *GoUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoUser.Marshal(b, m, deterministic)
}
func (m *GoUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoUser.Merge(m, src)
}
func (m *GoUser) XXX_Size() int {
	return xxx_messageInfo_GoUser.Size(m)
}
func (m *GoUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GoUser.DiscardUnknown(m)
}

var xxx_messageInfo_GoUser proto.InternalMessageInfo

func (m *GoUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GoUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GoUser) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *GoUser) GetBirthDay() int64 {
	if m != nil {
		return m.BirthDay
	}
	return 0
}

func (m *GoUser) GetSpouse() bool {
	if m != nil {
		return m.Spouse
	}
	return false
}

func (m *GoUser) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func init() {
	proto.RegisterType((*GoUser)(nil), "goserbench.GoUser")
}

func init() { proto.RegisterFile("gotest.proto", fileDescriptor_c3906679705eecf0) }

var fileDescriptor_c3906679705eecf0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xce, 0xbf, 0x6a, 0xc3, 0x30,
	0x10, 0xc7, 0x71, 0xce, 0x7f, 0x54, 0xf7, 0x28, 0xa5, 0x1c, 0xa5, 0x88, 0x4e, 0xa2, 0x93, 0xa6,
	0x2e, 0x79, 0x85, 0x40, 0x76, 0x41, 0x1e, 0x40, 0x8e, 0x0f, 0xdb, 0x83, 0x7d, 0x46, 0x52, 0x08,
	0x7e, 0x9f, 0x3c, 0x68, 0xb0, 0x12, 0xbc, 0xfd, 0x3e, 0x5f, 0x6e, 0x38, 0xfc, 0xe8, 0x25, 0x71,
	0x4c, 0xff, 0x4b, 0x90, 0x24, 0x84, 0xbd, 0x44, 0x0e, 0x2d, 0xcf, 0x97, 0xe1, 0xef, 0x0e, 0xa8,
	0x4e, 0x72, 0x8e, 0x1c, 0xe8, 0x13, 0x8b, 0xb1, 0xd3, 0x60, 0xc0, 0xbe, 0xbb, 0x62, 0xec, 0x88,
	0xb0, 0x9a, 0xfd, 0xc4, 0xba, 0xc8, 0x25, 0x6f, 0xfa, 0xc5, 0x66, 0xf1, 0x31, 0xde, 0x24, 0x74,
	0xba, 0xcc, 0x7d, 0x37, 0x7d, 0x61, 0xe9, 0x7b, 0xd6, 0x95, 0x01, 0x5b, 0xbb, 0x6d, 0x6e, 0xd7,
	0xed, 0x18, 0xd2, 0x70, 0xf4, 0xab, 0xae, 0x0d, 0xd8, 0xd2, 0xed, 0xa6, 0x1f, 0x54, 0x71, 0x91,
	0x6b, 0x64, 0xad, 0x0c, 0xd8, 0xc6, 0xbd, 0x44, 0xdf, 0x58, 0x4f, 0x32, 0xf3, 0xaa, 0xdf, 0x0c,
	0x58, 0x70, 0x4f, 0xb4, 0x2a, 0x7f, 0x7e, 0x78, 0x04, 0x00, 0x00, 0xff, 0xff, 0x36, 0xcc, 0x47,
	0x73, 0xc9, 0x00, 0x00, 0x00,
}
