
# Target::test
#
.PHONY: test
test:
	@echo ${CURDIR}
	@echo ${MAKE_VERSION}
	@echo ${MAKEFILE_LIST}
	@echo ${MAKECMDGOALS}
	@echo "$(.VARIABLES)" | tr ' ' '\015' | grep MAKEF
	@echo ${COMPILE.C}
	@echo ${OUTPUT_OPTION}
	@echo ${LOADLIBES}
	@echo ${LDLIBS}
	@echo ${LINK.o}
