#- name: Set authorized key
#  tags: ssh
#  authorized_key:
#      user: root
#      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: install dependent packages
  import_tasks: centos.yml
  when: ansible_distribution == "CentOS"
